### ISSUE TITLE
Support for Wardens in Toa

### ISSUE THREAD

**Issue by Violet-Vibes** [Runemker/OPRS-plugin-port-to-Runelite--#1]
Seems like the toa plugin is missing support for wardens/last boss, any plans on adding it?

**Comment by Runemker** [comment]
No plans to add support. Animations are also blocked for the last boss anyways.

**Comment by Violet-Vibes** [comment]
> No plans to add support. Animations are also blocked for the last boss anyways.

Are you sure they are blocked? The mistake tracker uses them and it works fine there, https://github.com/QuestingPet/ToaMistakeTracker
