### ISSUE TITLE
Inconsistent at ToA

### ISSUE THREAD

**Issue by KaeganJ** [Runemker/OPRS-plugin-port-to-Runelite--#4]
I'm not sure if you're maintaining this, figured I'd give you a heads up if you are. The ToA plugin seems to be inconsistent, first time I ran it I saw all the overlays, however after that I am no longer seeing Kephris standard attack overlay, and I don't see any overlays at the Wardens. I took a look through the plugins to see if it was something I could fix with my limited knowledge, but I couldn't figure anything out.

**Comment by Runemker** [comment]
Should be fixed now with Warden.
