### ISSUE TITLE
Error with Prayer.java

### ISSUE THREAD

**Issue by deathguard6** [Runemker/OPRS-plugin-port-to-Runelite--#7]
It seems that a recent RL update broke something with the Prayer section of the script

I get an error of cannot find symbol for each of the different prayers on compile. It is also very possible I am messing something else up though it use to work just fine. 

"error: cannot find symbol
    THICK_SKIN(Varbits.PRAYER_THICK_SKIN, 5.0D, WidgetInfo.PRAYER_THICK_SKIN),
                                                          ^
  symbol:   variable PRAYER_THICK_SKIN
  location: class WidgetInfo"

**Comment by Runemker** [comment]
Prayer widgets were removed in the [API](https://github.com/runelite/runelite/commit/e339b611d0fd27d835245d2c9206bf3bd86f043d). I don't maintain free public plugins. I'll tell you how to do it as it shouldn't be hard if you know what to modify. You'll need to import prayer WidgetID and WidgetInfo. Then get rid of all the widgetinfo referring to Prayer in the plugins as `(WidgetInfo.PRAYER_THICK_SKIN)` doesn't exist anymore to then use the imported widgetid/widgetinfo. When you run the compiler the errors should show up on all the plugins that use it. If you or anyone else can do it and make pull requests I will pull it into main.

**Comment by deathguard6** [comment]
I will give it a shot no promises I am not all that familiar with much more than basic coding but could be a fun thing to play around with. 

Cheers for the guidance.

**Comment by Runemker** [comment]
Fix in 692b019787326a0fd851d09daa219368630c69bf
